// Generated by Achaemenid Keyboard Generator
// Old Persian Cuneiform Keyboard - Web Layout

const ACHPKeyboard = {
name: "Achaemenid Keyboard",
id: "achp",
locale: "fa-IR",

keys: {
"Digit1": {
base: "1",
shift: "!",
ctrl: "𐏑"
},
"Digit2": {
base: "2",
shift: "@",
ctrl: "𐏒"
},
"Digit3": {
base: "3",
shift: "#",
ctrl: "𐏓"
},
"Digit4": {
base: "4",
shift: "$",
ctrl: "𐏔"
},
"Digit5": {
base: "5",
shift: "%",
ctrl: "𐏕"
},
"Digit6": {
base: "6",
shift: "^",
ctrl: "𐏖"
},
"Digit7": {
base: "7",
shift: "&",
ctrl: "𐏗"
},
"Digit8": {
base: "8",
shift: "*",
ctrl: "𐏘"
},
"Digit9": {
base: "9",
shift: "(",
ctrl: "𐏙"
},
"Digit0": {
base: "0",
shift: ")",
ctrl: "𐏚"
},
"KeyQ": {
base: "𐎤",
shift: "Q",
ctrl: ""
},
"KeyW": {
base: "𐎸",
shift: "W",
ctrl: ""
},
"KeyE": {
base: "𐎰",
shift: "E",
ctrl: ""
},
"KeyR": {
base: "𐎼",
shift: "R",
ctrl: ""
},
"KeyT": {
base: "𐎫",
shift: "T",
ctrl: ""
},
"KeyY": {
base: "𐎹",
shift: "Y",
ctrl: ""
},
"KeyU": {
base: "𐎢",
shift: "U",
ctrl: ""
},
"KeyI": {
base: "𐎡",
shift: "I",
ctrl: ""
},
"KeyO": {
base: "𐎢",
shift: "O",
ctrl: ""
},
"KeyP": {
base: "𐎱",
shift: "P",
ctrl: ""
},
"BracketLeft": {
base: "𐎩",
shift: "{",
ctrl: ""
},
"BracketRight": {
base: "𐎨",
shift: "}",
ctrl: ""
},
"KeyA": {
base: "𐎠",
shift: "A",
ctrl: ""
},
"KeyS": {
base: "𐎿",
shift: "𐏁",
ctrl: ""
},
"KeyD": {
base: "𐎭",
shift: "D",
ctrl: ""
},
"KeyF": {
base: "𐎳",
shift: "F",
ctrl: ""
},
"KeyG": {
base: "𐎥",
shift: "G",
ctrl: ""
},
"KeyH": {
base: "𐏃",
shift: "H",
ctrl: ""
},
"KeyJ": {
base: "𐎩",
shift: "J",
ctrl: ""
},
"KeyK": {
base: "𐎣",
shift: "K",
ctrl: ""
},
"KeyL": {
base: "𐎾",
shift: "L",
ctrl: ""
},
"KeyZ": {
base: "𐏀",
shift: "Z",
ctrl: ""
},
"KeyX": {
base: "𐎧",
shift: "X",
ctrl: ""
},
"KeyC": {
base: "𐎨",
shift: "C",
ctrl: ""
},
"KeyV": {
base: "𐎺",
shift: "V",
ctrl: ""
},
"KeyB": {
base: "𐎲",
shift: "B",
ctrl: ""
},
"KeyN": {
base: "𐎴",
shift: "N",
ctrl: ""
},
"KeyM": {
base: "𐎶",
shift: "M",
ctrl: ""
},
"Comma": {
base: "𐏐",
shift: "<",
ctrl: ""
},
"Period": {
base: "𐏐",
shift: ">",
ctrl: ""
},
"Minus": {
base: "-",
shift: "_",
ctrl: ""
},
"Equal": {
base: "=",
shift: "+",
ctrl: ""
},
"Semicolon": {
base: "𐏐",
shift: ":",
ctrl: ""
},
"Quote": {
base: "𐏐",
shift: "\"",
ctrl: ""
},
"Slash": {
base: "/",
shift: "?",
ctrl: ""
},
"Space": {
base: " ",
shift: " ",
ctrl: ""
},
}
};

function getACHPCharacter(key, modifiers = {}) {
const mapping = ACHPKeyboard.keys[key];

if (!mapping)
return null;

if (modifiers.ctrl)
return mapping.ctrl;

if (modifiers.shift)
return mapping.shift;

return mapping.base;
}
